export const tranlate = {
  home_page: {
    home: ["Home", "Trang chủ"],
    trending: ["Trending", "Xu hướng"],
    tags: [
      "Stories from all interests",
      "Câu chuyện từ các tag được yêu thích",
    ],
  },
  navbar: {
    search_blog: ["Search blog", "Tìm kiếm blog"],

    profile: ["Profile", "Hồ sơ"],

    sign_out: ["Sign Out", "Đăng xuất"],
  },
  authform: {
    password: ["Password", "Mật khẩu"],
    forgot_password: ["Forgot password?", "Quên mật khẩu?"],
    google: ["Continue with google", "Tiếp tục với google"],
    dont_have: ["Don't have an account", "Chưa có tài khoản"],
    fullname: ["Fullname", "Tên đầy đủ"],
    type_fullname: ["Type fullname", "Điền tên đầy đủ"],
    type_password: ["Type password", "Điền mật khẩu"],
    type_email: ["Type email", "Điền email"],
    have_had: ["Have you had an account?", "Bạn đã có tài khoản?"],
    or: ["Or", "Hoặc"],
    join_us: ["Join us today", "Tham gia vào cộng đồng"],
    welcome_back: ["Welcome back", "Chào mừng bạn đã quay trở lại"],
  },
  editor_page: {
    new_title: ["New title", "Tiêu đề mới"],
    publish: ["Publish", "Đăng"],
    save_draft: ["Save draft", "Lưu bản nháp"],
    title: ["Blog title", "Tiêu đề"],
    banner: ["Blog Banner", "Ảnh nền"],
    content: ["Let's write story", "Hãy viết nội dung"],
  },
  preview_page: {
    preview: ["Preview", "Xem trước"],
    description: ["Description", "Mô tả"],
    toppic: ["Toppic", "Chủ đề"],
    char_left: ["characters left", "ký tự còn lại"],
  },
  profile_page: {
    reads: ["Reads", "Lượt đọc"],
    published_blog: ["Published blogs", "Blogs đã đăng"],
    about_user: ["About user", "Thông tin thêm"],
    edit_profile: ["Edit profile", "Chỉnh sửa hồ sơ"],
  },
  dashboard_blogs: {
    drafts: ["Drafts", "Bản nháp"],
    likes: ["Likes", "Lượt thích"],
    comments: ["Comments", "Lượt bình luận"],
    reads: ["Reads", "Lượt đọc"],
    manage_blog: ["Manage blog", "Quản lý blog"],

    stats: ["Stats", "Trạng thái"],
  },
  dashboard_noti: {
    all: ["All", "Tất cả"],
    like: ["Like", "Yêu thích"],
  },
  change_pasword: {
    cp: ["Change pasword", "Thay đổi mật khẩu"],
    current_pass: ["Current password", "Mật khẩu hiện tại"],
    new_pass: ["New Password", "Mật khẩu mới"],
  },
  write: ["write", "Tạo blog mới"],
  sign_in: ["sign in", "đăng nhập"],
  sign_up: ["sign up", "đăng ký"],
  notifications: ["Notifications", "Thông báo"],
  dashboard: ["Dashboard", "Quản lý"],
  settings: ["Settings", "Cài đặt"],
  delete: ["Delete", "Xoá"],
  edit: ["Edit", "Chỉnh sửa"],
  published_on: ["Published on", "Đăng ngày"],
  comment: ["comment", "Bình luận"],
  all: ["all", "Tất cả"],
  like: ["like", "Thích"],
  reply: ["reply", "Phản hồi"],
  show: ["Show", "Hiển thị "],
  hidden: ["Hidden", "Ẩn"],
  load_more: ["Load more", "Tải thêm"],
  edit_profile: ["Edit profile", "Chỉnh sửa hồ sơ"],
  username_des: [
    "Username will use to search user and will be visible to everyone",
    "Username sẽ dùng để tìm kiếm người dung và hiển thị cho mọi người",
  ],
  social_link: [
    "Add your social links below",
    "Thêm đường dẫn mạng xã hội của bạn bên dưới",
  ],
  update: ["Update", "Cập nhật"],
  upload_image: ["Upload image", "Tải hình ảnh lên"],
  //   replied_on: [
  //     "replied on your comment on the blog",
  //     "đã phản hồi bình luận của bạn trên blog",
  //   ],
  like_your_blog: ["liked the blog", "đã thích blog "],
  commented_on: ["commented on your blog", "đã bình luận trên blog"],
  replied_on: [
    "replied on the comment on the blog",
    "đã phản hồi bình luận trên blog",
  ],
  minutes: ["minutes", "phút"],
  hours: ["hours", "giờ"],
  days: ["days", "ngày"],
  joined_at: ["joined at", "đã tham gia lúc"],
  page_not_found: {
    pnf: ["page not found", "Trang không tồn tại"],
    des: [
      "The page you are looking does not exists. Head back to the",
      "Trang bạn tìm không tồn tại. Quay lại",
    ],
    footer: [
      "Read millions of stories in the world",
      "Đọc hàng triệu câu chuyện trên toàn thế giới",
    ],
  },
  forgot_password: ["Forgot password", "Quên mật khẩu"],
  reset_password: ["Reset password", "Tạo mật khẩu mới"],
  send: ["Send", "Gửi"],
  view_all: ["view all", "Xem tất cả"],
  new: ["new", "mới"],
  confirm: ["Confirm", "Xác nhận"],
  cancel: ["Cacel", "Huỷ"],
  warn: [
    "Are you sure to delete this blog?",
    "Bạn có chắc chắn muốn xoá blog này không?",
  ],
  warning: ["Warning", "Cảnh báo"],
  delete_all: ["Delete all", "Xoá tất cả"],
  mark_as_read: ["Mark as read", "Đánh dấu đã đọc"],
  similar_blogs: ["Similar blogs", "Các blog tương tự"],
};
